# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-07-26 10:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fb', '0003_player_profile'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Player_Profile',
            new_name='Profile',
        ),
    ]
