# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-07-26 10:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fb', '0005_profile_username'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
