# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-07-26 11:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fb', '0007_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player_Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('email', models.EmailField(max_length=50)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_picture/%y%m%d')),
                ('age', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
